### ISSUE TITLE
Add avoidance and automatic retry for 401 failures

### ISSUE THREAD

**Issue by tyrw** [userfront/userfront-core#7]
We want to aid project users as much as possible, and we are offering access tokens that expire relatively quickly.

As a result, end users may encounter 401 errors from expired auth tokens.  We want our library to automatically do the following for each request:

1. Inspect the outgoing header. If it has `Authorization: Bearer ${accessToken}` with a Userfront access token, then perform a client-side check to verify that the token has not expired. If the access token has expired, then refresh it and add the new one to the header before making the request.
2. Make the request
3. If a 401 is received and the access token is more than 1 minute old, refresh the access token and repeat the request.

To complete this, we need a few things:
- [ ] Endpoint to retrieve JWT public RSA key based on tenantId. Probably should do so upon `Userfront.init()`
- [ ] Methods to read and verify the JWTs
- [ ] Method to check whether a header contains a Userfront access token (`true` even if expired, and `false` for non-Userfront tokens)
- [ ] Watcher on HTTP requests (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests)
- [ ] Method(s) to retry the request
- [ ] Method to refresh the access and ID tokens
